### PR TITLE
Feature/gabhijit izel 72 74 remove hardcoded

### PR DESCRIPTION
**Pull request by gabhijit-izel**
## Description
Removed following hard coded descriptions - 

1. VLAN attribute
2. VLAN interface name
3. quali network 

1 and 2 now come as Cloud Provider attributes

## Related Stories

#15

## Breaking
YES 

## Breaking changes
-  Data model has changed now.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/openstack-shell/81)

### CODE REVIEW

**Comment by alexazarh** [comment]
Reviewed 7 of 16 files at r1.
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[drivers/openstack_shellPackage/Configuration/shellconfig.xml, line 20 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81#-KYSU7OgvEHxtjfRgzKx:-KYSU7OgvEHxtjfRgzKy:b-bslt5n) ([raw file](https://github.com/qualisystems/openstack-shell/blob/078989831b9c653ed2ea7dc9c0bbba953fc9a61d/drivers/openstack_shellPackage/Configuration/shellconfig.xml#L20)):*
> ```XML
>               <Attribute Name="Reserved Networks" Value="" />
>               <Attribute Name="Quali Management Network UUID" Value=""/>
>               <Attribute Name="Provider Network Type" Value=""/>
> ```

The name of the attribute should be "Vlan Type" according to https://github.com/QualiSystems/Azure-Shell/issues/218

---

*[drivers/openstack_shellPackage/Configuration/shellconfig.xml, line 21 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81#-KYSUQWkAQinnFO9TKOn:-KYSUQWliQFsBIjIPAvc:b2ybooc) ([raw file](https://github.com/qualisystems/openstack-shell/blob/078989831b9c653ed2ea7dc9c0bbba953fc9a61d/drivers/openstack_shellPackage/Configuration/shellconfig.xml#L21)):*
> ```XML
>               <Attribute Name="Quali Management Network UUID" Value=""/>
>               <Attribute Name="Provider Network Type" Value=""/>
>               <Attribute Name="Provider Network Interface" Value=""/>
> ```

What is the purpose of this attribute?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81)*

**Comment by gabhijit-izel** [comment]
*[drivers/openstack_shellPackage/Configuration/shellconfig.xml, line 21 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81#-KYSUQWkAQinnFO9TKOn:-KYTE2jr2Jdqe-ugMNC1:b-adsxm5) ([raw file](https://github.com/qualisystems/openstack-shell/blob/078989831b9c653ed2ea7dc9c0bbba953fc9a61d/drivers/openstack_shellPackage/Configuration/shellconfig.xml#L21)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

What is the purpose of this attribute?
</blockquote></details>

This attribute is required during creating network . When we create a network there's a required attribute 'provider:physical_interface' that specifies which physical interface is to be used for this network on a given node. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81)*

**Comment by gabhijit-izel** [comment]
*[drivers/openstack_shellPackage/Configuration/shellconfig.xml, line 20 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81#-KYSU7OgvEHxtjfRgzKx:-KYTEO0mA2NM9jSjBpWM:b9esyac) ([raw file](https://github.com/qualisystems/openstack-shell/blob/078989831b9c653ed2ea7dc9c0bbba953fc9a61d/drivers/openstack_shellPackage/Configuration/shellconfig.xml#L20)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

The name of the attribute should be "Vlan Type" according to https://github.com/QualiSystems/Azure-Shell/issues/218
</blockquote></details>

Ok. Will take care of this and update the review request.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81)*

**Comment by gabhijit-izel** [comment]
*[drivers/openstack_shellPackage/Configuration/shellconfig.xml, line 20 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81#-KYSU7OgvEHxtjfRgzKx:-KYXLW2cg56l9wyJRtgq:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/078989831b9c653ed2ea7dc9c0bbba953fc9a61d/drivers/openstack_shellPackage/Configuration/shellconfig.xml#L20)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Ok. Will take care of this and update the review request.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81)*

**Comment by alexazarh** [comment]
Reviewed 4 of 16 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/81)*

**Pull request merged**
