### PR TITLE
Feature/gabhijit izel 66 affinity groups

### PR DESCRIPTION
**Pull request by gabhijit-izel**
## Description

Affinity Group Support for Apps 

Affinity Group ID is taken as App deployment model attribute. If this is presents Apps are deployed in that affinity group (that is on same instance)

## Breaking
YES 

## Breaking changes

Datamodel changes in App deployment model.

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/openstack-shell/125)

### CODE REVIEW

**Comment by alexazarh** [comment]
Reviewed 1 of 8 files at r1.
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 90 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG4_lVN6Qj7XMvV9Bi:-KbG4_lVN6Qj7XMvV9Bj:b-1wvcez) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L90)):*
> ```Python
>                                                    instance=instance,
>                                                    floating_ip=floating_ip)
>             # Wait till floating IP obj is deleted???
> ```

if remove_floating_ip is removing the floating ip asynchronously than we should wait for the operation to compelte

---

*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 315 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG3L4rrZ3MjGxnwEmA:-KbG3L4s8aeSzXHFJAzS:b78vfs7) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L315)):*
> ```Python
>             if fl.ip == floating_ip:
>                 floating_ip_objid = fl.id
>                 break
> ```

If we had the floating ip saved could we avoid this loop?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 315 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG3L4rrZ3MjGxnwEmA:-KbG_CzxBGrWqNYTk_5V:b-f6rzr4) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L315)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

If we had the floating ip saved could we avoid this loop?
</blockquote></details>

You mean floating_ip_object_id? Yes - if we there is a way to save that, we can avoid this loop since this "object_id" is required by the API. Not sure how to save this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 90 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG4_lVN6Qj7XMvV9Bi:-KbGZoVywyG508XNWe1V:bxr8ag) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L90)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

if remove_floating_ip is removing the floating ip asynchronously than we should wait for the operation to compelte
</blockquote></details>

Yes - This is an asynchronous operation. But if this operation is not complete, the port_delete and subsequent instance_delete should ideally get synchronized on this operation by OpenStack. So I marked this comment here. I am not entirely sure whether we should be waiting for this. But kept a comment there - just in case we should visit it again?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 90 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG4_lVN6Qj7XMvV9Bi:-Kb_JJhYwGvixCtCkOyx:bs0sgx9) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L90)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Yes - This is an asynchronous operation. But if this operation is not complete, the port_delete and subsequent instance_delete should ideally get synchronized on this operation by OpenStack. So I marked this comment here. I am not entirely sure whether we should be waiting for this. But kept a comment there - just in case we should visit it again?
</blockquote></details>

Checked this up - While internal API communication might be asynchronous - Once the API returns, the floating IP is deleted. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 90 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG4_lVN6Qj7XMvV9Bi:-Kb_JcPYtFs4gykgJLap:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L90)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Checked this up - While internal API communication might be asynchronous - Once the API returns, the floating IP is deleted. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 315 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG3L4rrZ3MjGxnwEmA:-Kb_Je_mLQyknczm3xdq:b4tjwc9) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L315)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

You mean floating_ip_object_id? Yes - if we there is a way to save that, we can avoid this loop since this "object_id" is required by the API. Not sure how to save this?
</blockquote></details>

Used a different API called "find" rather than simply "list" this allows to find by attributes. No need to store ID and use it subsequently. Much simpler now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py, line 315 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125#-KbG3L4rrZ3MjGxnwEmA:-Kb_Jq0iqxm_xacXU38Q:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/b17802c6c4aee48c8170186115bd86dc8354a641/package/cloudshell/cp/openstack/domain/services/nova/nova_instance_service.py#L315)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Used a different API called "find" rather than simply "list" this allows to find by attributes. No need to store ID and use it subsequently. Much simpler now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by alexazarh** [comment]
Reviewed 5 of 8 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Comment by alexazarh** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/125)*

**Pull request merged**
