### PR TITLE
Feature/gabhijit izel 22 autoload

### PR DESCRIPTION
**Pull request by gabhijit-izel**
## Description
Autooad Feature

## Breaking
NO

## Breaking changes
- ### Breaking change description
      Detailed change info 
      Migration steps

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/openstack-shell/119)

### CODE REVIEW

**Comment by alexazarh** [comment]
*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 30 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam51dD9LANNkr4kQK:-Kaam51dD9LANNkr4kQL:b-7kf0ix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L30)):*
> ```Python
>         logger = get_qs_logger(log_group='Autoload',
>                                log_file_prefix=context.resource.name,
>                                log_category="OpenStackShell")
> ```

should be passed to the validate method like we do with the operations

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by alexazarh** [comment]
Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drivers/openstack_shell/src/driver.py, line 55 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalm86Y5uz1MmOrbFW:-Kaalm86Y5uz1MmOrbFX:bh8hhx9) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/driver.py#L55)):*
> ```Python
> 
>         # This will raise exception if there's a problem or else we fall through to AutoLoadDetails
>         cp_validator.validate_all()
> ```

this should be in the package and not in the shell drive

---

*[drivers/openstack_shell/src/requirements.txt, line 4 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalttb84cJKufCp2m_:-Kaalttb84cJKufCp2ma:b-eig9oa) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/requirements.txt#L4)):*
> ```
> cloudshell-cp-openstack<1.0.0
> jsonpickle
> python-keystoneclient>=3.1.0,<=3.8.0
> ```

this requirements should not be here

---

*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 24 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam0I3JGyRFt9bOW5h:-Kaam0I3JGyRFt9bOW5i:b-eydrcw) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L24)):*
> ```Python
> 
>         # Get CP Resource Object
>         self.model_parser = OpenStackShellModelParser()
> ```

should be injected as a dependency, the same is relevant to all objects that are created in the contstructor

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
*[drivers/openstack_shell/src/driver.py, line 55 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalm86Y5uz1MmOrbFW:-KaazAWbKqR-IYbSNSSB:bt0iiw8) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/driver.py#L55)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

this should be in the package and not in the shell drive
</blockquote></details>

I am looking at the vCenter code. Do you mean the line below should be there in the package and not the lines above right? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 24 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam0I3JGyRFt9bOW5h:-Kaazl1CA_x1WdHYDac1:b-kkza9m) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L24)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

should be injected as a dependency, the same is relevant to all objects that are created in the contstructor
</blockquote></details>

Didn't get it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 30 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam51dD9LANNkr4kQK:-Kaazr2F2jpH0M-tjcoG:b-r25ys6) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L30)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

should be passed to the validate method like we do with the operations
</blockquote></details>

But this is available as a property of the class in all validate methods if we need it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
*[drivers/openstack_shell/src/requirements.txt, line 4 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalttb84cJKufCp2m_:-Kab--L4kdKdjT5qm_Qv:b-3uz9wr) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/requirements.txt#L4)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

this requirements should not be here
</blockquote></details>

Sorry - this came during testing and got left as it is. Will remove this once all changes are approved. This helps a lot during testing. Will remove it 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 24 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam0I3JGyRFt9bOW5h:-KahWojtqzTCU4SLUdp_:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L24)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Didn't get it. 
</blockquote></details>

Done.

---

*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 30 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam51dD9LANNkr4kQK:-KahWsa9lI4Y0Yjuc9T8:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L30)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

But this is available as a property of the class in all validate methods if we need it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by gabhijit-izel** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drivers/openstack_shell/src/driver.py, line 55 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalm86Y5uz1MmOrbFW:-KahXJ31JIosyycYDknb:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/driver.py#L55)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

I am looking at the vCenter code. Do you mean the line below should be there in the package and not the lines above right? 
</blockquote></details>

Done.

---

*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 24 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam0I3JGyRFt9bOW5h:-KahXMqlxrPN1nstIV5n:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L24)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py, line 30 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaam51dD9LANNkr4kQK:-KahXOWdmC3RAwRtAFZF:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/package/cloudshell/cp/openstack/domain/services/cp_validators/cp_validator.py#L30)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[drivers/openstack_shell/src/requirements.txt, line 4 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-Kaalttb84cJKufCp2m_:-KahXQaUkPFyluAEFhqY:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/fc0fb7351891f823a7b7c196c24ac20a0300964b/drivers/openstack_shell/src/requirements.txt#L4)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Sorry - this came during testing and got left as it is. Will remove this once all changes are approved. This helps a lot during testing. Will remove it 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by alexazarh** [comment]
*[package/cloudshell/cp/openstack/domain/services/cp_validators/__init__.py, line 0 at r3](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119#-KakwH61itinfi3gKzEx:-KakwH61itinfi3gKzEy:bnxnf2b) ([raw file](https://github.com/qualisystems/openstack-shell/blob/5ba54235d37b98e5f5649ca31c5df1b1b7f2d4c0/package/cloudshell/cp/openstack/domain/services/cp_validators/__init__.py#L0)):*
The init should not be empty. All init files in the python package should contain the following:

__author__ = 'quali'
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Comment by alexazarh** [comment]
Reviewed 1 of 6 files at r1, 2 of 6 files at r2, 4 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/119)*

**Pull request merged**
