### PR TITLE
 #95 fix. All error messages are now reported to user correctly

### PR DESCRIPTION
**Pull request by gabhijit-izel**
Nova error messages raise exceptions during deploy (etc).
 Neutron error messages are reported as errorMessage in connectivityResult

## Description

Fixed error reporting during deploy and connectivity. Right errors are now reported to user

## Breaking
NO

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/openstack-shell/131)

### CODE REVIEW

**Comment by alexazarh** [comment]
Reviewed 3 of 6 files at r1, 2 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/openstack/domain/services/connectivity/vlan_connectivity_service.py, line 115 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFH1bK8OdGc_G516-:-KbLFH1bK8OdGc_G5160:b-gp9ekt) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/connectivity/vlan_connectivity_service.py#L115)):*
> ```Python
>                 logger.error(traceback.format_exc())
>                 net_err_msg = "{0} {1}".format(type(e), e.message)
>                 net_err_msg = net_err_msg.replace("<", "(").replace(">", ")")
> ```

The replace repeats several times in code. I think it should be extracted to a helper method.

---

*[package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py, line 49 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFYI7GlVMJ8ZNYiIr:-KbLFYI7GlVMJ8ZNYiIs:b-6a3syh) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py#L49)):*
> ```Python
>             new_net = new_net['networks'][0]
>         except Exception as e:
>             raise
> ```

this is redundant. we can remove the "except Exception".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py, line 49 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFYI7GlVMJ8ZNYiIr:-KbNabHPAT0-WHtCGdK1:bg7rvmp) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py#L49)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

this is redundant. we can remove the "except Exception".
</blockquote></details>

No this is not - client.list_networks - can indeed throw an exception or client.create_network can throw another exception. Only NetCreateConflict is caught to re-use if the network already exists. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py, line 49 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFYI7GlVMJ8ZNYiIr:-KbYgqTxZDyj--9-2bPF:b-h2o3gl) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py#L49)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

No this is not - client.list_networks - can indeed throw an exception or client.create_network can throw another exception. Only NetCreateConflict is caught to re-use if the network already exists. 
</blockquote></details>

Well - there is no need to Catch and Raise that explicitly - Removed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131)*

**Comment by gabhijit-izel** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package/cloudshell/cp/openstack/domain/services/connectivity/vlan_connectivity_service.py, line 115 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFH1bK8OdGc_G516-:-KbYgoL1ydG59byxNz4I:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/connectivity/vlan_connectivity_service.py#L115)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

The replace repeats several times in code. I think it should be extracted to a helper method.
</blockquote></details>

Done.

---

*[package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py, line 49 at r2](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131#-KbLFYI7GlVMJ8ZNYiIr:-KbYgx0MrG69Aksw0SfD:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/a3d90f7053af68c27208a6748a35a6f366c6a3c5/package/cloudshell/cp/openstack/domain/services/neutron/neutron_network_service.py#L49)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Well - there is no need to Catch and Raise that explicitly - Removed 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131)*

**Comment by alexazarh** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/131)*

**Pull request merged**
