### PR TITLE
Feature/gabhijit izel 17 floating ips

### LINKED ISSUE #42: Remove Cloud Provider related attributes for Floating IP and Security Groups
As discussed in the current release, we are not planning to support Floating IP and Security groups as this may not be required. We should be removing the floating IP and security group related attributes from Cloud Provider and Deployment App attributes

### PR DESCRIPTION
**Pull request by gabhijit-izel**
## Description
Implementation of #17. Also fixes #42 and #34 
## Related Stories

#42 and #34 

## Breaking
YES 

## Breaking changes

Modified the Datamodel

---
This change is [Reviewable](https://reviewable.io/reviews/qualisystems/openstack-shell/100)

### CODE REVIEW

**Comment by alexazarh** [comment]
Reviewed 6 of 15 files at r1.
Review status: 6 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py, line 50 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100#-K_PHrbei0ngCQAjebn7:-K_PHrbei0ngCQAjebn8:b-g5480s) ([raw file](https://github.com/qualisystems/openstack-shell/blob/6e712750dd672e77763369b5a4800bf220c8e327/package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py#L50)):*
> ```Python
> 
>         floating_ip = public_ip
>         cloudshell_session.SetAttributeValue(resource_fullname, RefreshIPOperation.public_ip, floating_ip)
> ```

Where is the get for the latest public ip?
Or the public ip can never change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100)*

**Comment by gabhijit-izel** [comment]
*[package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py, line 50 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100#-K_PHrbei0ngCQAjebn7:-K_YMiMr9Xh74JjZGZBU:bb6un1j) ([raw file](https://github.com/qualisystems/openstack-shell/blob/6e712750dd672e77763369b5a4800bf220c8e327/package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py#L50)):*
<details><summary><i>Previously, alexazarh wrote…</i></summary><blockquote>

Where is the get for the latest public ip?
Or the public ip can never change?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100)*

**Comment by gabhijit-izel** [comment]
Review status: 5 of 13 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py, line 50 at r1](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100#-K_PHrbei0ngCQAjebn7:-K_YMlnC5GQBnDiKwK38:b-896fix) ([raw file](https://github.com/qualisystems/openstack-shell/blob/6e712750dd672e77763369b5a4800bf220c8e327/package/cloudshell/cp/openstack/command/operations/refresh_ip_operation.py#L50)):*
<details><summary><i>Previously, gabhijit-izel wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100)*

**Comment by alexazarh** [comment]
Reviewed 5 of 15 files at r1, 3 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qualisystems/openstack-shell/100)*

**Pull request merged**
